// Builds the self-hosted web fonts from the OFL sources in /fonts-src.
//  - subsets each font to the characters Margin needs (Latin incl. DE/FR, typographic punctuation)
//  - keeps the weight axis (pins Inter's optical-size axis)
//  - writes woff2 files to /public/fonts
//  - writes vertical metrics to src/theme/font-metrics.json (used for ruled-line baseline alignment)
//  - writes the "margin" wordmark and favicon glyph outlines from Caveat to src/brand/wordmark-paths.json
// Run: npm run fonts:build   (outputs are committed; only re-run when fonts or the charset change)
import fs from 'node:fs/promises';
import path from 'node:path';
import subsetFont from 'subset-font';
import opentype from 'opentype.js';
const { parse } = opentype;

const root = path.resolve(import.meta.dirname, '../..');
const src = (f) => path.join(root, 'fonts-src', f);

const range = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => String.fromCodePoint(a + i)).join('');
export const CHARSET =
  range(0x20, 0x7e) + // Basic Latin
  range(0xa0, 0xff) + // Latin-1 Supplement (ä ö ü ß é è à ç « » …)
  'ŒœŸ' + // the only Latin Extended-A letters French/German need
  '  ' + // thin / narrow no-break space (kept when the font has them)
  '‐‑–—‘’‚‛“”„‟•…‹›′″€≈×→←↗✓·°½¼¾²³±−';

const FONTS = [
  { family: 'Caveat', file: 'Caveat-wght.ttf', out: 'caveat.woff2', axes: { wght: { min: 400, max: 700 } } },
  { family: 'Playpen Sans', file: 'PlaypenSans-wght.ttf', out: 'playpen-sans.woff2', axes: { wght: 400 } },
  { family: 'Inter', file: 'Inter-opsz-wght.ttf', out: 'inter.woff2', axes: { opsz: 14, wght: { min: 400, max: 600 } } },
];

const metrics = {};
for (const f of FONTS) {
  const buf = await fs.readFile(src(f.file));
  const woff2 = await subsetFont(buf, CHARSET, { targetFormat: 'woff2', variationAxes: f.axes });
  await fs.writeFile(path.join(root, 'public/fonts', f.out), woff2);

  const font = parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
  const upm = font.unitsPerEm;
  const os2 = font.tables.os2;
  const hhea = font.tables.hhea;
  const useTypo = Boolean(os2.fsSelection & (1 << 7));
  // The metrics browsers actually use: typo metrics when USE_TYPO_METRICS is set, otherwise hhea.
  const ascent = (useTypo ? os2.sTypoAscender : hhea.ascender) / upm;
  const descent = Math.abs(useTypo ? os2.sTypoDescender : hhea.descender) / upm;
  const lineGap = (useTypo ? os2.sTypoLineGap : hhea.lineGap) / upm;
  metrics[f.family] = {
    file: f.out,
    ascent: +ascent.toFixed(4),
    descent: +descent.toFixed(4),
    lineGap: +lineGap.toFixed(4),
    xHeight: +(os2.sxHeight / upm).toFixed(4),
    capHeight: +(os2.sCapHeight / upm).toFixed(4),
    bytes: woff2.length,
  };
  console.log(`${f.family.padEnd(14)} ${(woff2.length / 1024).toFixed(1)} KB  asc=${ascent} desc=${descent}`);
}
await fs.writeFile(path.join(root, 'src/theme/font-metrics.json'), JSON.stringify(metrics, null, 2) + '\n');

// Wordmark + favicon outlines: instance Caveat at a fixed weight, then read glyph paths.
const caveat = await fs.readFile(src('Caveat-wght.ttf'));
const staticTtf = await subsetFont(caveat, 'margin', { targetFormat: 'truetype', variationAxes: { wght: 600 } });
const cav = parse(staticTtf.buffer.slice(staticTtf.byteOffset, staticTtf.byteOffset + staticTtf.byteLength));
const SIZE = 100;
const word = cav.getPath('margin', 0, 0, SIZE);
const box = word.getBoundingBox();
const m = cav.getPath('m', 0, 0, SIZE);
const mBox = m.getBoundingBox();
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => (+n).toFixed(1));
await fs.writeFile(
  path.join(root, 'src/brand/wordmark-paths.json'),
  JSON.stringify(
    {
      note: 'Generated by scripts/fonts/build-fonts.mjs from Caveat (OFL) at wght 600, font size 100. Baseline is y=0.',
      word: { d: round(word.toPathData(2)), x1: box.x1, y1: box.y1, x2: box.x2, y2: box.y2 },
      m: { d: round(m.toPathData(2)), x1: mBox.x1, y1: mBox.y1, x2: mBox.x2, y2: mBox.y2 },
    },
    null,
    2,
  ) + '\n',
);
console.log('wrote font-metrics.json and wordmark-paths.json');
